In [2]:
#Testing that PyTorch installation worked

import torch
x = torch.rand(5, 3,2)
print(x)

tensor([[[0.3572, 0.7988],
         [0.8031, 0.6855],
         [0.5933, 0.4272]],

        [[0.3962, 0.4648],
         [0.8030, 0.8706],
         [0.6400, 0.3019]],

        [[0.5260, 0.5805],
         [0.2401, 0.6582],
         [0.8747, 0.3347]],

        [[0.2344, 0.7701],
         [0.8131, 0.2663],
         [0.0386, 0.0294]],

        [[0.0112, 0.0913],
         [0.6588, 0.4464],
         [0.0662, 0.7312]]])


In [2]:
#Creating a Random Tensor and finding information about it

import torch

some_tensor = torch.rand(2,3,4)

print(some_tensor)

print(f"Shape of Tensor: {some_tensor.shape}")

print(f"Datatype of Tensor: {some_tensor.dtype}")

print(f"Device tensor is stored on: {some_tensor.device}")

#you can change the type that the tensor data is, that sometimes can be a problem when you operate on tensors of multiple data types
#you can also make tensors filled with ones and zeros of the same shape as another tensor

tensor([[[0.8533, 0.2788, 0.4509, 0.6202],
         [0.2252, 0.8942, 0.0885, 0.6250],
         [0.9649, 0.0143, 0.6016, 0.6849]],

        [[0.6172, 0.1632, 0.6188, 0.3977],
         [0.3237, 0.0819, 0.3450, 0.6866],
         [0.1347, 0.4409, 0.2723, 0.0467]]])
Shape of Tensor: torch.Size([2, 3, 4])
Datatype of Tensor: torch.float32
Device tesnor is stored on: cpu


In [9]:
#Matrix Multiplication

#pretty much everything in ML/AI is just some form of matrix manipulation, especially matrix multiplications (dot products)

import torch

tensor_one = torch.tensor([[2,3,4],[2,3,4]])
tensor_two = torch.tensor([[1,2],[2,3],[3,4]])
print(tensor_one.shape, tensor_two.shape)
new_tensor = torch.matmul(tensor_one, tensor_two)
print(new_tensor.shape)
#to be able to do matrix multiplication on matrices, the inner values have to match, and the resulting matrix is takes the shape of the outside values

#other operations are very simple
t_one_modified = tensor_one + 10
print(t_one_modified)

#mismatched shapes are a common type of error in deep learning, and you can solve this by transposing


torch.Size([2, 3]) torch.Size([3, 2])
torch.Size([2, 2])
tensor([[12, 13, 14],
        [12, 13, 14]])


In [14]:
#Messing around with Feed Forward Layers
import torch

# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [19]:
#aggregation

# Create a tensor
x = torch.arange(0, 100, 10)

print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error, the dtype is int64
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

#using torch methods works the same
#print(torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x))



Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450
tensor(90) tensor(0) tensor(45.) tensor(450)


In [20]:
#finding positions of maximums and minimums

import torch

# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [21]:
#Tensor type errors

#another type of error is running into tensors of different datatypes, you can also make the datatype less precise to make computations easier/faster(int64 -> int8)

import torch

# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
print(tensor.dtype)

# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
print(tensor_float16)


# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
print(tensor_int8)


torch.float32
tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)
tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)
